version: '3.7'

services:
# ## BACKEND
#   api:
#     container_name: flask_rest_api
#     build: .
#     depends_on:
#       - db
#       - redis
#     env_file:
#       - ./src/.env
#     environment:
#       - SERVICE=api
#     networks:
#       - default
#     ports:
#       - 5000:5000
#       - 5002:5000
#     volumes:
#       - ./src:/src

# ## REDIS
#   redis:
#     image: redis:alpine
#     container_name: redis
#     hostname: redis
#     ports:
#       - "6379:6379"

# ## CELERY WORKER
#   worker:
#     restart: always
#     build:
#       context: .
#     hostname: worker
#     entrypoint: celery
#     command: -A run.celery worker -l info
#     volumes:
#       - ./src:/src
#     links:
#       - redis
#     env_file:
#       - ./src/.env
#     environment:
#       - SERVICE=celery
#     depends_on:
#       - redis
#       - db
#       - api

# ## FLOWER
#   flower:
#     image: mher/flower:1.0.0
#     build:
#       context: .
#     entrypoint: celery
#     command: -A run.celery flower -l info -p 5555
#     volumes:
#       - ./src:/src
#     ports:
#       - 5555:5555
#     env_file:
#       - ./src/.env
#     environment:
#       - SERVICE=flower
#     depends_on:
#       - worker
#       - redis
#       - api

## DB
  db:
    image: postgres:13-alpine
    container_name: customers_db
    env_file:
      - ./customers/.env
    networks:
      - default
    ports:
      - 5430:5432
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
