"""empty message

Revision ID: 2c0abeaabef4
Revises: be7e5345f24e
Create Date: 2022-08-25 15:08:07.257839

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '2c0abeaabef4'
down_revision = 'be7e5345f24e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address', 'fake')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('fake', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
