"""empty message

Revision ID: be7e5345f24e
Revises: 0ca22bf0c809
Create Date: 2022-08-25 15:07:42.958750

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'be7e5345f24e'
down_revision = '0ca22bf0c809'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('fake', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address', 'fake')
    # ### end Alembic commands ###
