"""empty message

Revision ID: e62435c6512f
Revises: a9c22a3798e8
Create Date: 2022-08-22 21:24:15.586676

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'e62435c6512f'
down_revision = 'a9c22a3798e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'address', 'customer', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'address', type_='foreignkey')
    op.drop_column('address', 'customer_id')
    # ### end Alembic commands ###
